version: '3'
services:
  api:
    environment:
      - DEBUG=True
      - API_HOST=http://localhost:8000
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOSTNAME=db
      - DB_USER=dataminr
      - DB_PASSWORD=db_pass
      - DB_NAME=dataminr
      - OPEN_WEATHER_KEY=8e98e84f1f292798d75564a97bbd9d06