services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: db_pass
      POSTGRES_USER: dataminr
      POSTGRES_DB: dataminr
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
  api:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOSTNAME=db
      - DB_USER=dataminr
      - DB_PASSWORD=db_pass
      - DB_NAME=dataminr
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db-data:
