# Generated by Django 4.0.4 on 2022-04-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='observer',
            new_name='observers',
        ),
    ]
